---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Generates a pull request on demand
name: 'Generate Pull Request â¬‡ï¸'

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  schedule:
    - cron: '40 6 * * 0'

permissions: {}

jobs:
  generate-pr:
    name: 'Generate Pull Request â¬‡ï¸'
    runs-on: 'ubuntu-24.04'
    permissions:
      # Needed to add/update a file in the repository
      contents: write
      # Needed to raise the pull request
      pull-requests: write
      # Needed to create pull request labels
      issues: write

    timeout-minutes: 5
    steps:
      - name: 'Harden runner ğŸ”’'
        # yamllint disable-line rule:line-length
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: 'audit'

      # yamllint disable-line rule:line-length
      - name: 'Checkout local repository â˜‘ï¸'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: 'List existing pull requests ğŸ“‹'
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          # List pull requests with label/search
          requests=$(gh pr list -l 'automated pr')
          if [ -n "$requests" ]; then
            echo 'Pull requests ğŸ’¬'
            echo "$requests"
          fi

      - name: "Running local action: ${{ github.repository }} ğŸ”¨"
        uses: ./
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
